### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [ElenaLaufeyson/Polynom_Java#1]
0. Самостоятельный вызов `System.gc()` - плохой стиль. Так не нужно делать ~~почти~~ никогда. Виртуальная машина Java сама соберёт мусор, когда это необходимо. 
1. Надо ли хранить степень полинома в явном виде? Она ведь всегда равна `array.length + 1`
2. В методе `toString()` вы очень много раз используете конкатенацию строк. При каждой конкатенации в Java строка копируется. Используйте `StringBuilder`.
3. Метод `invert` меняет текущий полином, а остальные арифметические методы создают новый. Выберете один стиль, а лучше реализуйте оба набора операций: изменяющие объект и создающие новый (как, например, у целых чисел, (`+`, `+=`, `-`, `-=` и т. д., но в виде методов `plus`, `plusEquals`, `minus`, `minusEquals` и т. д.). Один набор легко реализуется через другой.
4. Метод `cut0()` явно вспомогательный и внешнему пользователю не нужен. Если он совершает допустимые вами операции с вашим объектом, то полином всегда будет в нормальной форме. Следует объявить его приватным.
5. В `cut0` вы создаёте полином `cutPol` только ради того, чтобы скопировать массив `this.array`. Почему бы просто не скопировать массив?
6. Флаг `resb` у `div` -- плохое решение при проектировании программного интерфейса. (Вы же не сделали флаг `addb` у метода сложения, чтобы он мог вычитать.). Разбейте операцию деления и взятия остатка на отдельные методы

**Comment by ElenaLaufeyson** [comment]
Я исправила все замечания, кроме 1.
Я понимаю, что степень полинома всегда равна array.lenght - 1, но лично я считаю, что хранить степень полинома в явном виде нагляднее и понятнее, а также не нужно будет каждый раз считать ее снова.

**Comment by gagarski** [comment]
Для наглядности понятности вы можете вынести вычисление степени полинома в метод, который будет вычислять её из длины массива. Это, как минимум, уменьшит простор для потенциальных ошибок (нужно поддерживать это значение в актуальном состоянии при изменении массива). Особенно нелепо явная степень выглядит в конструкторе (пользователь класса сам должен правильно вычислить степень и передать её).

**Comment by gagarski** [comment]
Ещё: поле `array` можно сделать приватным.

**Comment by ElenaLaufeyson** [comment]
Все исправила

**Comment by gagarski** [comment]
Ещё то, что ускользнуло от взгляда:
1. Полином по заданию должен быть целочисленным, у вас его коэффициенты -- double
2. У вас нельзя получить доступ к содержимому полинома никак, кроме как превратив его в строку. Не помешает метод `int getCoefficient(int degree)`, получающий коэффициент полинома, соттветствующий указанной степени. Метод `getDegree` внешнему пользователю вашего класса тоже не помешает, можно его сделать публичным.
